[project]
name = "statescape"
version = "0.1.0"
description = "StateScape: Conformational Sampling Pipeline for Protein Dynamics"
readme = "README.md"
authors = [
    { name = "Emiliano Salinas", email = "esalinasbio@gmail.com" },
    { name = "Alejandro Sosa", email = "asosa@bq.unam.mx" }
]
requires-python = ">=3.10"
dependencies = [
    "mdtraj>=1.10.3",
    "natsort>=8.4.0",
    "netcdf4>=1.7.3",
    "openmm>=8.5.1",
    "pdbfixer>=1.12.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "tmtools>=0.3.0",
    "tqdm>=4.67.3",
    "umap-learn>=0.5.12",
]

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]

[tool.statescape.vendored]
amino = { source = "https://github.com/tiwarylab/af2rave", commit = "794c6a2", vendored = "2026-05-27", license = "MIT" }