[project]
name = "statescape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Emiliano Salinas", email = "esalinasbio@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mdtraj>=1.10.3",
    "natsort>=8.4.0",
    "netcdf4>=1.7.3",
    "pdbfixer>=1.12.0",
    "propka>=3.5.1",
    "scikit-learn>=1.7.2",
    "tmtools>=0.3.0",
    "umap-learn>=0.5.12",
]

[project.scripts]
statescape = "statescape:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
