from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

SOLUTE_HEAVY = "!:WAT,Na+,K+,Cl- & !@H="

THERMOSTATS = {
    "langevin": {"ntt": 3, "gamma_ln": 2.0},
    "andersen": {"ntt": 2, "vrand": 1000},
    "berendsen": {"ntt": 1, "tautp": 1.0},
}
BAROSTATS = {
    "berendsen": {"barostat": 1, "taup": 1.0},
    "montecarlo": {"barostat": 2},
}


@dataclass(frozen=True)
class Stage:
    """
    A stage in a MD protocol

    Parameters
    ----------
    name : stage name
    mdin : pmemd input text
    repeats : number of chained runs of `mdin` (restart stages only, irest=1)
    executable : overrides `run(executable=...)` for this stage
    fallback : executable used once if the stage fails (e.g. 'pmemd' on CPU)
    """
    name: str
    mdin: str
    repeats: int = 1
    executable: str | Sequence[str] | None = None
    fallback: str | Sequence[str] | None = None

    @property
    def restrained(self) -> bool:
        return re.search(r"\bntr\s*=\s*1\b", self.mdin, re.IGNORECASE) is not None

    @classmethod
    def from_file(cls, name: str, path: str | Path, **kwargs) -> Stage:
        """Stage from a user-written pmemd input file."""
        return cls(name, Path(path).read_text(), **kwargs)


def _steps(ps: float, dt: float) -> int:
    n = ps / dt
    if abs(n - round(n)) > 1e-6:
        raise ValueError(f"{ps} ps is not a whole number of {dt} ps steps.")
    return int(round(n))


def _pick(table: dict, key: str, what: str) -> dict:
    if key not in table:
        raise ValueError(f"Unknown {what} {key!r}. Available: {list(table)}")
    return dict(table[key])


def _restraint(weight: float, mask: str) -> dict:
    return dict(ntr=1, restraint_wt=weight, restraintmask=mask) if weight > 0 else {}


def _render(name: str, cntrl: dict, extra: str = "") -> str:
    body = ",\n".join(f"  {k}={v!r}" if isinstance(v, str) else f"  {k}={v}" for k, v in cntrl.items())
    return f"{name}: generated by statescape\n &cntrl\n{body},\n /\n{extra}"


def _dynamics(ps, dt, temperature, cutoff, thermostat, save_every_ps) -> dict:
    nstlim = _steps(ps, dt)
    nsave = min(_steps(save_every_ps, dt), nstlim)
    return dict(
        imin=0, nstlim=nstlim, dt=dt, ntc=2, ntf=2, cut=cutoff,
        temp0=temperature, ig=-1, **_pick(THERMOSTATS, thermostat, "thermostat"),
        ntpr=nsave, ntwx=nsave, ntwr=min(nstlim, _steps(1000.0, dt)), ntxo=2, ioutfm=1, iwrap=1,
    )


def minimization(
    *,
    name: str = "min",
    sd_steps: int = 5000,
    cg_steps: int = 5000,
    restraint_wt: float = 0.0,
    restraint_mask: str = SOLUTE_HEAVY,
    cutoff: float = 8.0,
    cntrl: dict | None = None,
    fallback: str | Sequence[str] | None = "pmemd",
) -> Stage:
    """Steepest descent followed by conjugate gradient minimization."""
    c = dict(imin=1, maxcyc=sd_steps + cg_steps, ncyc=sd_steps, ntb=1, ntc=2, cut=cutoff, ntpr=100, ntxo=2,
             **_restraint(restraint_wt, restraint_mask))
    c.update(cntrl or {})
    return Stage(name, _render(name, c), fallback=fallback)


def heating(
    *,
    name: str = "heat",
    ps: float = 50.0,
    hold_ps: float = 10.0,
    temperature: float = 300.0,
    restraint_wt: float = 2.0,
    restraint_mask: str = SOLUTE_HEAVY,
    dt: float = 0.002,
    cutoff: float = 8.0,
    thermostat: str = "langevin",
    save_every_ps: float = 1.0,
    cntrl: dict | None = None,
    fallback: str | Sequence[str] | None = "pmemd",
) -> Stage:
    """NVT heating: linear ramp 0 K -> `temperature` over `ps - hold_ps`, then keep the same temp"""
    if not 0 <= hold_ps < ps:
        raise ValueError(f"hold_ps must be in [0, ps), got {hold_ps} for ps={ps}.")
    c = _dynamics(ps, dt, temperature, cutoff, thermostat, save_every_ps)
    c.update(irest=0, ntx=1, ntb=1, tempi=0.0, nmropt=1, **_restraint(restraint_wt, restraint_mask))
    c.update(cntrl or {})
    ramp, n = _steps(ps - hold_ps, dt), c["nstlim"]
    wt = f" &wt type='TEMP0', istep1=0, istep2={ramp}, value1=0.0, value2={temperature} /\n"
    if ramp < n:
        wt += f" &wt type='TEMP0', istep1={ramp + 1}, istep2={n}, value1={temperature}, value2={temperature} /\n"
    wt += " &wt type='END' /\n"
    return Stage(name, _render(name, c, wt), fallback=fallback)


def npt(
    name: str,
    *,
    ps: float,
    repeats: int = 1,
    temperature: float = 300.0,
    restraint_wt: float = 0.0,
    restraint_mask: str = SOLUTE_HEAVY,
    barostat: str = "berendsen",
    pressure: float = 1.0,
    dt: float = 0.002,
    cutoff: float = 8.0,
    thermostat: str = "langevin",
    save_every_ps: float = 1.0,
    cntrl: dict | None = None,
    fallback: str | Sequence[str] | None = "pmemd",
) -> Stage:
    """NPT dynamics restarted from the previous stage. `ps` is the length of each repeat."""
    c = _dynamics(ps, dt, temperature, cutoff, thermostat, save_every_ps)
    c.update(irest=1, ntx=5, ntb=2, ntp=1, pres0=pressure, **_pick(BAROSTATS, barostat, "barostat"),
             **_restraint(restraint_wt, restraint_mask))
    c.update(cntrl or {})
    return Stage(name, _render(name, c), repeats=repeats, fallback=fallback)


def production(
    *,
    name: str = "prod",
    ns: float = 10.0,
    temperature: float = 300.0,
    barostat: str = "montecarlo",
    pressure: float = 1.0,
    dt: float = 0.002,
    cutoff: float = 8.0,
    thermostat: str = "langevin",
    save_every_ps: float = 10.0,
    cntrl: dict | None = None,
    fallback: str | Sequence[str] | None = None,
) -> Stage:
    """Unrestrained NPT production."""
    return npt(name, ps=ns * 1000, temperature=temperature, barostat=barostat, pressure=pressure, dt=dt,
               cutoff=cutoff, thermostat=thermostat, save_every_ps=save_every_ps, cntrl=cntrl, fallback=fallback)


def default_protocol(
    *,
    temperature: float = 300.0,
    production_ns: float = 10.0,
    save_every_ps: float = 10.0,
) -> list[Stage]:
    """Minimal protocol: 2x minimization, NVT heating, NPT density (5x10 ps), NPT equilibration, production."""
    return [
        minimization(name="min1", restraint_wt=10.0),
        minimization(name="min2"),
        heating(temperature=temperature),
        npt("density", ps=10.0, repeats=5, temperature=temperature, restraint_wt=1.0),
        npt("equil", ps=200.0, temperature=temperature),
        production(ns=production_ns, temperature=temperature, save_every_ps=save_every_ps),
    ]